apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-ms
  template:
    metadata:
      labels:
        app: message-ms
    spec:
      initContainers:
        - name: wait-for-rabbit
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -zv rabbitmq-service 5672; do echo waiting for rabbit; sleep 2; done;",
            ]
      containers:
        - name: message-ms
          image: message-ms:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
          env:
            - name: JWT_BASE64_URL_ENCODED
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: jwt-base64-encode
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbit-secrets
                  key: rabbit-user
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit-secrets
                  key: rabbit-password
            - name: RABBIT_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbit-secrets
                  key: rabbit-host
---
apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  selector:
    app: message-ms
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
data:
  # base64 encode of a base64url encoded string
  jwt-base64-encode: U0VsVVNFVlNSVWhQVjFsUFZVUlBTVTVIVkU5RVFWbEpTRTlRUlVWV1JWSlpWRWhKVGtkSlUwZFBUMFE=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:latest
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
          ports:
            - containerPort: 5672
            - containerPort: 61613
          command:
            - bash
            - -c
            - |
              rabbitmq-plugins enable --offline rabbitmq_stomp && rabbitmq-server

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbit
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: stomp
      protocol: TCP
      port: 61613
      targetPort: 61613

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secrets
data:
  rabbit-host: cmFiYml0bXEtc2VydmljZQ==
  rabbit-user: Z3Vlc3Q=
  rabbit-password: Z3Vlc3Q=
